# This workflow will install Python dependencies, run Nasdaq Data Fetcher script to update the database
name: Nasdaq Listings Fetcher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */4 * * *"

jobs:
  Fetch_Nasdaq_Listings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f ./Ingestion/requirements.txt ]; then pip install -r ./Ingestion/requirements.txt; fi
    - name: Setup DB Connection Environment Variable
      run: |
        echo "nasdaq_db=${{ secrets.nasdaq_prod_db }}" >> $GITHUB_ENV
    - name: Fetch Data from Nasdaq Api
      run: |
        python3 start_fetcher.py
